### ISSUE TITLE
Some formatting chars show up in message

### ISSUE THREAD

**Issue by dargueta** [dylang/logging#6]
Formatting characters inconsistently show up in the message. For example, `(INFO) blah` shows up as `INFO blah` with "INFO" in cyan, as expected. However `!ERROR! blah` appears exactly as written - `!ERROR! blah` which is inconsistent with the previous behavior. The problem appears [here](https://github.com/dylang/logging/blob/master/lib/logging.js#L65-L68) and is rather simple to fix - you only need to call `substring` as you do with the other colors.

**Comment by dylang** [comment]
Hi @dargueta thanks for your issues. I haven't worked on this library for about 5 years. I recommend more flexible libraries like https://github.com/trentm/node-bunyan.

**Comment by dylang** [comment]
I've re-written the library, so this ticket is not valid any more.
