### ISSUE TITLE
Bolding does not work

### ISSUE THREAD

**Issue by dargueta** [dylang/logging#7]
Contrary to the last commit made, bolding a color by doubling `!!` doesn't work.

Using Node.js v5.5.0 on OSX:
<img width="249" alt="screen shot 2016-02-03 at 12 28 40 am" src="https://cloud.githubusercontent.com/assets/620513/12776722/4186c8ba-ca0d-11e5-9238-4f96e470ec42.png">

**Comment by dylang** [comment]
Hi @dargueta thanks for your issues. I haven't worked on this library for about 5 years. I recommend more flexible libraries like https://github.com/trentm/node-bunyan.

**Comment by dylang** [comment]
I've re-written the library, so this ticket is not valid any more.
